# Generated by Django 4.2.11 on 2024-04-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('codcat', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('libcat', models.CharField(max_length=30)),
            ],
        ),
    ]
