# Generated by Django 4.2.11 on 2024-04-04 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_produit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('codeprod', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('libprod', models.CharField(max_length=30)),
                ('pu', models.IntegerField()),
                ('qte', models.IntegerField()),
                ('codcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_produit.categorie')),
            ],
        ),
    ]
